#!/bin/bash

# 使用 `envsubst` 将模板文件中的 ${NGINX_PORT} 替换为实际的环境变量值
envsubst '${NGINX_PORT}' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf
# 自动更新
git clone -b main https://github.com/jxxghp/MoviePilot.git /tmp/app
pip install --upgrade pip
pip install -r /tmp/app/requirements.txt
git clone -b main https://github.com/jxxghp/MoviePilot-Frontend.git /tmp/web
cd /tmp/web
yarn
yarn build
rm -rf /app
mv /tmp/app /app
rm -rf /public
mv /tmp/web/dist /public
cd /app
rm -rf /tmp/web /tmp/app
# 更改 moviepilot userid 和 groupid
groupmod -o -g ${PGID} moviepilot
usermod -o -u ${PUID} moviepilot
# 更改文件权限
chown -R moviepilot:moviepilot \
    ${HOME} \
    /app \
    /public \
    /config \
    /var/lib/nginx \
    /var/log/nginx
chown moviepilot:moviepilot /etc/hosts /tmp
# 下载浏览器内核
gosu moviepilot:moviepilot playwright install chromium
# 启动前端nginx服务
nginx
# 设置后端服务权限掩码
umask ${UMASK}
# 启动后端服务
exec dumb-init gosu moviepilot:moviepilot python3 app/main.py