#!/bin/bash

git clone -b main --depth=1 https://github.com/jxxghp/MoviePilot.git /tmp/app
pip install --upgrade pip
pip install -r /tmp/app/requirements.txt
ACTION_ID=$(curl -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" \
    https://api.github.com/repos/${GITHUB_REPO}/actions/workflows | jq '.workflows[] | select(.name == "Build moviepilot frontend") | .id')
curl -X POST \
    -H "Authorization: token ${GITHUB_TOKEN}" \
    -H "Accept: application/vnd.github.v3+json" \
    https://api.github.com/repos/${GITHUB_REPO}/actions/workflows/${ACTION_ID}/dispatches \
    -d '{"ref":"docker"}'
sleep 150
git clone -b web --depth=1 https://github.com/${GITHUB_REPO}.git /tmp/web
rm -rf /app
mv /tmp/app /app
rm -rf /public
mv /tmp/web /public
rm -rf /tmp/web /tmp/app
echo "程序更新成功"